"use client";

import { useState } from "react";

const finishes = [
  { id: "gel", name: "3D Gel", detail: "Gloss with a little depth", price: 34 },
  { id: "four", name: "4D Acrylic", detail: "Sculpted, confident lettering", price: 44 },
  { id: "five", name: "5D Carbon", detail: "A sportier finish", price: 54 },
  { id: "hex", name: "Hex", detail: "A modern raised profile", price: 48 },
];

function Arrow() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-7-7 7 7-7 7"/></svg>; }
function Plate({ reg, finish }: { reg: string; finish: string }) { return <div className={`plate plate-${finish}`}><span className="plate-country"><b>✦</b><small>UK</small></span><strong>{reg || "YOUR REG"}</strong></div>; }

export default function PremiumHome() {
  const [reg, setReg] = useState("PP24 LUX");
  const [finish, setFinish] = useState("four");
  const [menu, setMenu] = useState(false);
  const [basket, setBasket] = useState(false);
  const [added, setAdded] = useState(false);
  const selected = finishes.find((f) => f.id === finish) ?? finishes[1];
  return <main id="top">
    <div className="topline"><span className="topline-dot"/> MADE TO ORDER IN THE UK <i>·</i> <span>YOUR FINISH. YOUR DETAILS. YOUR CAR.</span></div>
    <header className="header"><a href="#top" className="brand" aria-label="Premium Plates home"><span className="brand-symbol">P<span>·</span>P</span><span className="brand-text">PREMIUM<br/><b>PLATES</b></span></a><nav className="nav"><a href="#finishes">Plate styles</a><a href="#craft">Our approach</a><a href="#details">The details</a></nav><div className="head-right"><a href="#studio" className="head-cta">Design your plates <Arrow/></a><button className="basket-btn" aria-label="Open basket" onClick={() => setBasket(true)}>BAG <span>{added ? "01" : "00"}</span></button><button className="menu-btn" aria-label="Toggle menu" onClick={() => setMenu(!menu)}>{menu ? "CLOSE" : "MENU"}</button></div></header>
    {menu && <nav className="mobile-nav"><a onClick={() => setMenu(false)} href="#finishes">Plate styles <Arrow/></a><a onClick={() => setMenu(false)} href="#craft">Our approach <Arrow/></a><a onClick={() => setMenu(false)} href="#details">The details <Arrow/></a><a onClick={() => setMenu(false)} href="#studio">Design your plates <Arrow/></a></nav>}
    <section className="hero"><div className="hero-visual"><div className="hero-glow"/><div className="hero-floor"/><div className="car-shape"><div className="car-glass"/><div className="car-trunk"/><div className="car-tail-light"/><div className="hero-reg"><Plate reg="PP 24" finish="four"/></div><div className="car-wheel wheel-a"/><div className="car-wheel wheel-b"/></div><span className="visual-caption">PREMIUM PLATES STUDIO <i>·</i> UK</span></div><div className="hero-copy"><p className="kicker light"><i/> THE LAST DETAIL, DONE PROPERLY</p><h1>Make the<br/>whole car <em>yours.</em></h1><p className="hero-desc">Number plates with a little more presence. Choose your finish, make it yours, give your car the detail it deserves.</p><a className="btn btn-ivory" href="#studio">Design your plates <Arrow/></a><span className="hero-note">A considered finish for the cars you care about.</span></div><div className="hero-count"><b>01</b><i/>03</div><a className="scroll-cue" href="#studio">SCROLL TO EXPLORE <span>↓</span></a></section>
    <section className="statement" id="craft"><p>Good design lives in the details.</p><span>That’s where we start.</span><a href="#details">OUR APPROACH <Arrow/></a></section>
    <section className="studio" id="studio"><div className="section-head"><p className="kicker"><i/> THE PLATE STUDIO <span>01 — 04</span></p><h2>A small detail.<br/><em>A different feeling.</em></h2><p>Choose the finish that feels right. See it take shape as you go.</p></div><div className="builder"><div className="preview"><div className="preview-top"><span>LIVE PREVIEW</span><span>01 / 01</span></div><div className="preview-well"><div className="well-glow"/><div className="showcase-plate"><Plate reg={reg.toUpperCase() || "YOUR REG"} finish={finish}/></div><span className="well-caption">PERSONALISED FOR YOU</span></div><div className="preview-bottom"><span>YOUR {selected.name.toUpperCase()} PLATE</span><span>UK STANDARD FORMAT</span></div></div><div className="controls"><div className="step-title"><span>01</span><div><b>Enter a registration</b><small>Try yours to see it come to life.</small></div></div><label htmlFor="reg">YOUR REGISTRATION</label><div className="reg-field"><input id="reg" maxLength={8} value={reg} placeholder="e.g. PP24 LUX" onChange={(e) => setReg(e.target.value.replace(/[^a-zA-Z0-9 ]/g, "").toUpperCase())}/><span>✓</span></div><div className="step-title step-next"><span>02</span><div><b>Choose your finish</b><small>Each one has its own character.</small></div></div><div className="finish-list">{finishes.map((f, index) => <button key={f.id} className={`finish-choice ${finish === f.id ? "is-selected" : ""}`} onClick={() => setFinish(f.id)} aria-pressed={finish === f.id}><span className="choice-no">0{index + 1}</span><span className="choice-name"><b>{f.name}</b><small>{f.detail}</small></span><span className="choice-price">£{f.price}.00</span><i/></button>)}</div><div className="buy-row"><div><small>YOUR PAIR, FROM</small><b>£{selected.price}.00</b></div><button className="btn btn-dark" onClick={() => { setAdded(true); setBasket(true); }}>Add to basket <Arrow/></button></div><p className="price-note">MVP example pricing · confirm before launch</p></div></div></section>
    <section className="finishes" id="finishes"><div className="finish-heading"><div><p className="kicker"><i/> FIND YOUR FINISH</p><h2>Different character.<br/><em>Same attention to detail.</em></h2></div><p>Four ways to finish the rear of your car. Start with the look you like; the rest is in the detail.</p></div><div className="finish-grid">{finishes.map((f, i) => <a key={f.id} href="#studio" onClick={() => setFinish(f.id)} className={`finish-card card-${f.id}`}><div className="card-scene"><span className="card-no">0{i + 1} / 04</span><div className="card-plate"><Plate reg="PP 24" finish={f.id}/></div><span className="card-view">VIEW FINISH <Arrow/></span></div><div className="card-caption"><div><b>{f.name}</b><small>{f.detail}</small></div><span>£{f.price}.00 <Arrow/></span></div></a>)}</div></section>
    <section className="craft" id="details"><div className="craft-art"><span className="orbit orbit-one"/><span className="orbit orbit-two"/><div className="craft-surface"><Plate reg="PP 24" finish="five"/></div><div className="craft-label">A CLOSER LOOK <i/> 02 / 04</div></div><div className="craft-text"><p className="kicker"><i/> IT’S IN THE FINISH</p><h2>Close enough<br/>to notice.<br/><em>Made to last.</em></h2><p className="craft-desc">A crisp edge. A confident profile. A finish at home on the car you spent time choosing. No fuss. Just considered details, done right.</p><div className="benefits"><div><span>01</span><p><b>Made for your car</b><small>Choose the look that suits it.</small></p></div><div><span>02</span><p><b>Built around your reg</b><small>Preview your own details live.</small></p></div><div><span>03</span><p><b>The right final touch</b><small>Designed to complement, not compete.</small></p></div></div><a className="under-link" href="#studio">FIND YOUR FINISH <Arrow/></a></div></section>
    <section className="service-bar"><div><b>Made to order</b><small>Finished for your registration</small></div><div><b>Road-ready options</b><small>Choose a compliant style</small></div><div><b>UK delivery</b><small>Options shown at checkout</small></div><a href="#studio">MAKE YOURS <Arrow/></a></section>
    <section className="endcap"><div><p className="kicker light"><i/> YOUR CAR, FINISHED</p><h2>It’s the detail<br/>you’ll notice <em>every day.</em></h2></div><a className="btn btn-ivory" href="#studio">Start designing <Arrow/></a><span className="end-monogram">P<span>·</span>P</span></section>
    <footer className="footer"><a href="#top" className="brand"><span className="brand-symbol">P<span>·</span>P</span><span className="brand-text">PREMIUM<br/><b>PLATES</b></span></a><span>A considered finish for the cars you care about.</span><small>© 2026 PREMIUM PLATES</small><a href="#top">BACK TO TOP ↑</a></footer>
    {basket && <div className="drawer-scrim" onMouseDown={(e) => { if (e.target === e.currentTarget) setBasket(false); }}><aside className="drawer"><button className="drawer-x" aria-label="Close basket" onClick={() => setBasket(false)}>×</button><p className="kicker"><i/> YOUR SELECTION</p><h2>{added ? "A good choice." : "Your basket."}</h2>{added ? <div className="drawer-item"><Plate reg={reg || "YOUR REG"} finish={finish}/><div><b>{selected.name} pair</b><small>{reg || "Your registration"}</small></div><strong>£{selected.price}.00</strong></div> : <p className="drawer-empty">Your basket is waiting for a little detail.</p>}<div className="drawer-total"><span>Estimated total</span><b>£{added ? selected.price : 0}.00</b></div><p className="drawer-demo">Demo basket only. Checkout is not connected.</p><button className="btn btn-dark drawer-continue" onClick={() => setBasket(false)}>Keep exploring <Arrow/></button></aside></div>}
  </main>;
}
